### ISSUE TITLE
CUDA kernel failed when infer

### ISSUE THREAD

**Issue by YuxiangChai** [VAST-AI-Research/TriplaneGaussian#3]
I got this error when I tried to run `infer.py`:
```
CUDA kernel failed : no kernel image is available for execution on the device
void group_points_kernel_wrapper(int, int, int, int, int, const float*, const int*, float*) at L:38 in /mnt/data/mmlab_ee/yxchai/TriplaneGaussian/tgs/models/snowflake/pointnet2_ops_lib/pointnet2_ops/_ext-src/src/group_points_gpu.cu
```

Environment:
- RTX 3090
- CUDA 11.3
- Pytorch 1.12.1

This happens in line `model(batch)` in `infer.py`

**Comment by jmorgan-wellovate** [comment]
> I got this error when I tried to run `infer.py`:
> 
> ```
> CUDA kernel failed : no kernel image is available for execution on the device
> void group_points_kernel_wrapper(int, int, int, int, int, const float*, const int*, float*) at L:38 in /mnt/data/mmlab_ee/yxchai/TriplaneGaussian/tgs/models/snowflake/pointnet2_ops_lib/pointnet2_ops/_ext-src/src/group_points_gpu.cu
> ```
> 
> Environment:
> 
> * RTX 3090
> * CUDA 11.3
> * Pytorch 1.12.1
> 
> This happens in line `model(batch)` in `infer.py`

Are you using conda or pip install pytorch?

**Comment by zouzx** [comment]
It seems the problem of pointnet2_ops. Is the pointnet2_ops successfully installed? Maybe this solution from https://github.com/VAST-AI-Research/TriplaneGaussian/issues/1#issuecomment-1902514471 can help? We have updated the `setup.py` for auto-detection of TORCH_CUDA_ARCH_LIST, or you can manually set your own TORCH_CUDA_ARCH_LIST at https://github.com/VAST-AI-Research/TriplaneGaussian/blob/d0be64958cd62fc9033344849f0fc9daa4eafede/tgs/models/snowflake/pointnet2_ops_lib/setup.py#L20-L21.

**Comment by YuxiangChai** [comment]
> It seems the problem of pointnet2_ops. Is the pointnet2_ops successfully installed? Maybe this solution from [#1 (comment)](https://github.com/VAST-AI-Research/TriplaneGaussian/issues/1#issuecomment-1902514471) can help? We have updated the `setup.py` for auto-detection of TORCH_CUDA_ARCH_LIST, or you can manually set your own TORCH_CUDA_ARCH_LIST at
> 
> https://github.com/VAST-AI-Research/TriplaneGaussian/blob/d0be64958cd62fc9033344849f0fc9daa4eafede/tgs/models/snowflake/pointnet2_ops_lib/setup.py#L20-L21
> 
> .

Thanks! This works!
